### ISSUE TITLE
Generate via go generate?

### ISSUE THREAD

**Issue by incubus8** [devimteam/microgen#32]
Hi devimteam,

It's very helpful project 👍 
Can I also use with built in go:generate https://blog.golang.org/generate? Any example?

Thanks

**Comment by Vetcher** [comment]
It is simple, add to your `service.go`
```
//go:generate microgen
```
or 
```
//go:generate microgen -force
```
but I'm not ensure, that flag force works correct at this time.

BTW:
You may want to add protobuf compilation, if you use grpc transport:
```
//go:generate protoc --go_out=plugins=grpc: etc...
```

**Comment by incubus8** [comment]
Hi @Vetcher thanks, that helps
