### ISSUE TITLE
Some imports are non existing

### ISSUE THREAD

**Issue by Raffo** [devimteam/microgen#40]
Some imports do not exist, see for example in https://github.com/devimteam/microgen/blob/3b735130ad1ac71a796623e07c4a450e3431fa7f/example/generated/transport/converter/protobuf/endpoint_converters.go#L8 which imports `github.com/devimteam/protobuf`.

**Comment by Vetcher** [comment]
Right now main.go should compile and you will see message `constructor not provided`

**Comment by Raffo** [comment]
Great. I will wait for the commit / bugfix to land in the master branch.
