### ISSUE TITLE
Proposal: use methods annotation to customize http methods

### ISSUE THREAD

**Issue by Raffo** [devimteam/microgen#47]
When writing HTTP APIs I would love to use the right HTTP methods to model my API. I would love to use GET methods for "read" requests and POST for creating new things. 
This could be implemented by method annotations, something like: 

```

// @microgen http, middleware, logging, recover, main
type StringService interface {
        // @post
	SaveString(ctx context.Context, name string) (str string, err error)
	// @get
        GetStrings(ctx context.Context) (str string, err error)
}
```

In this way, it should be in theory possible to generate a REST api that looks okay such that clients of this API can use it while not running go or microgen. 

What do you think?

**Comment by Vetcher** [comment]
Nice idea, some time ago I were thinking about different http methods.

**Comment by Raffo** [comment]
I even have a bit of code to do that, I will try to submit a PR later today to get familiar with the code generation part if you don't mind.

**Comment by Vetcher** [comment]
I think, it would be hard to work directly with templates code, but you may try =)

**Comment by Raffo** [comment]
A first proposal here: https://github.com/devimteam/microgen/pull/48 ... it seem to work but I would love feedback on the solution and it can definitely be better and tests can be added (even though the coverage of tests can be improved all over the project probably).

**Comment by Raffo** [comment]
This was implemented, closing.
