### ISSUE TITLE
Error when generating project layout

### ISSUE THREAD

**Issue by uzmo** [devimteam/microgen#61]
MacBook-Pro:gokit2 mengk$ microgen -out .
@microgen 0.9.0
fatal: error when parse file: open /Users/mengk/GoProj/src/gokit2/service.go: no such file or directory
MacBook-Pro:gokit2 mengk$ microgen -out ./..
@microgen 0.9.0
fatal: error when parse file: open /Users/mengk/GoProj/src/gokit2/service.go: no such file or directory

**Comment by vetcher** [comment]
Did you have file `/Users/mengk/GoProj/src/gokit2/service.go`?

**Comment by vetcher** [comment]
Closing due to author's silence
@uzmo open new issue if this one does not resolved for you
